/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ProdutoLojaDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.fornecedores.Produto;
import model.loja.ProdutoLoja;
import tabacariaControllers.Tabacaria;
import utils.DateUtils;
import utils.parse.StringNormalizer;
import view.comboboxModel.GeneralComboboxModel;
import view.tableModel.GeneralTableModel;

/**
 *
 * @author andre
 */
public class JPanelProduto extends javax.swing.JPanel {

     /**
     * Creates new form MainJFrame
     */
    private Tabacaria ctr;
    private GeneralTableModel<Produto> tmProduto;
    
   
    
    public JPanelProduto(Tabacaria ctrl) {
        this.ctr = ctrl;
        initComponents();
        this.updateTableProdutos(this.ctr.getProdutos());
    }
    
    
    private Produto getSelectedProduto(){
        int selectedIndex = this.jTableProdutos.getSelectedRow();
        if(selectedIndex < 0){
            return null;
        }
        
        Produto p =  this.tmProduto.getObjectAt(selectedIndex);
        return p;
    }
    
    
    /**************************************/
    
    private void updateTableProdutos(List<Produto> prods){
        String [] columns = new String[4];

        columns[0] = "id";
        columns[1] = "nome";
        columns[2] = "descricao";
        columns[3] = "preco";
        
        this.tmProduto = new GeneralTableModel<Produto>(columns, prods);
        this.jTableProdutos.setModel(this.tmProduto);
    }
    
    /*****************************************************************************/
    
    private void showSelectedProduto(){
        // TODO add your handling code here:
        System.err.println("DEBUG: jTableProdutosPropertyChange");
        
        Produto selected = this.getSelectedProduto();
        
        if(selected == null){
            System.err.println("PRODUTO SELECIONADO É NULL");
            return;
        }
        
        /*******************/
        
        try{
            ProdutoLojaDao pjDao = new ProdutoLojaDao();
            System.err.println("ID PRODUTO A RECUPERAR PREÇO DE VENDA: " + selected.getId());
            List<ProdutoLoja> ljPrds = pjDao.executeQuery("FROM ProdutoLoja AS ProdutoLoja WHERE produto_id = '"+  selected.getId() +"'");
            ProdutoLoja ploja = ljPrds.size() >= 1 ? ljPrds.get(0) : null;
            
            if(ploja != null){
                this.jFormattedTextFieldPrecoVenda.setText(utils.parse.NumberParser.DoubleToDecimalString(ploja.getPrecoVenda()));
            }else{
                 this.jFormattedTextFieldPrecoVenda.setText(utils.parse.NumberParser.DoubleToDecimalString(selected.getPreco()));
            }
        }
        catch(Exception e){
           e.printStackTrace();
        }
        
        /********************/
        
        this.jListSelectedProduto.removeAll();
        
        List<Produto> lstSelected = new ArrayList<>();
        lstSelected.add(selected);
        
        this.jListSelectedProduto.setModel(new GeneralComboboxModel<Produto>().getComboBoxModelUsingDescription(lstSelected));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProdutos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        descField = new javax.swing.JTextField();
        pRadioBtn = new javax.swing.JRadioButton();
        modeField = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        priceField = new javax.swing.JFormattedTextField();
        pDateField = new javax.swing.JFormattedTextField();
        vDateField = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        fornecedorField1 = new javax.swing.JFormattedTextField();
        jTextFieldPesquisaProdutos = new javax.swing.JTextField();
        jButtonPesquisaProdutos = new javax.swing.JButton();
        jButtonShowAll = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jListSelectedProduto = new javax.swing.JList<>();
        jButtonAtualizarProduto = new javax.swing.JButton();
        jButtonRemoverProduto = new javax.swing.JButton();
        jButtonComprarProduto = new javax.swing.JButton();
        jFormattedTextFieldQuantidade = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPrecoVenda = new javax.swing.JFormattedTextField();

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Menu Produtos");

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableProdutos.setShowVerticalLines(false);
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jTableProdutos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableProdutosPropertyChange(evt);
            }
        });
        jTableProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableProdutosKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(jTableProdutos);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Produto"));

        nameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do produto"));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        descField.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição do produto"));

        pRadioBtn.setText("Perecível");

        modeField.setBorder(javax.swing.BorderFactory.createTitledBorder("Modo de conservação"));

        registerBtn.setText("Cadastrar");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        priceField.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço"));
        priceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        pDateField.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de produção"));
        pDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        vDateField.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de validade"));
        vDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jButton1.setText("Selecionar fornecedor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fornecedorField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedor"));
        fornecedorField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(pRadioBtn)
                                        .addGap(148, 148, 148))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(registerBtn)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fornecedorField1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modeField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fornecedorField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(pRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modeField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerBtn)
                .addGap(40, 40, 40))
        );

        jButtonPesquisaProdutos.setText("Pesquisar");
        jButtonPesquisaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaProdutosActionPerformed(evt);
            }
        });

        jButtonShowAll.setText("Mostrar todos");
        jButtonShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllActionPerformed(evt);
            }
        });

        jListSelectedProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));
        jListSelectedProduto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane11.setViewportView(jListSelectedProduto);

        jButtonAtualizarProduto.setText("Atualizar produto selecionado");
        jButtonAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarProdutoActionPerformed(evt);
            }
        });

        jButtonRemoverProduto.setText("Remover produto selecionado");
        jButtonRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverProdutoActionPerformed(evt);
            }
        });

        jButtonComprarProduto.setText("Comprar produto selecionado");
        jButtonComprarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarProdutoActionPerformed(evt);
            }
        });

        jFormattedTextFieldQuantidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));
        jFormattedTextFieldQuantidade.setText("1");

        jFormattedTextFieldPrecoVenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço de venda"));
        jFormattedTextFieldPrecoVenda.setText("10.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(jButtonRemoverProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonComprarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonAtualizarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoverProduto))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonComprarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelProdutosLayout = new javax.swing.GroupLayout(jPanelProdutos);
        jPanelProdutos.setLayout(jPanelProdutosLayout);
        jPanelProdutosLayout.setHorizontalGroup(
            jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutosLayout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisaProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanelProdutosLayout.setVerticalGroup(
            jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelProdutosLayout.createSequentialGroup()
                        .addGroup(jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisaProdutos)
                            .addComponent(jButtonShowAll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
        // TODO add your handling code here:
        this.showSelectedProduto();
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void jTableProdutosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableProdutosPropertyChange
        this.showSelectedProduto();
    }//GEN-LAST:event_jTableProdutosPropertyChange

    private void jTableProdutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProdutosKeyPressed
        // TODO add your handling code here:
        this.showSelectedProduto();
    }//GEN-LAST:event_jTableProdutosKeyPressed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        if(nameField.getText().isEmpty() || descField.getText().isEmpty() || priceField.getText().isEmpty() /*| idField.getText().isEmpty()*/){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
        }else if((pRadioBtn.isSelected()) && (modeField.getText().isEmpty() || vDateField.getText().isEmpty() || pDateField.getText().isEmpty())){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
        }else{
            try{
                if(!this.pRadioBtn.isSelected()){
                    System.err.println("INTERFACE: CADASTRANDO PRODUTO NORMAL");
                    this.ctr.addProduto(
                        0,
                        this.nameField.getText(),
                        this.descField.getText(),
                        utils.parse.NumberParser.getFloatFrom(this.priceField.getText())
                    );
                }else{
                    System.err.println("INTERFACE: CADASTRANDO PRODUTO PERECÍVEL");
                    this.ctr.addProduto(
                        DateUtils.fromString(this.pDateField.getText()),
                        DateUtils.fromString(this.vDateField.getText()),
                        this.modeField.getText(),
                        0,
                        this.nameField.getText(),
                        this.descField.getText(),
                        utils.parse.NumberParser.getFloatFrom(this.priceField.getText())
                    );
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Algum campo não foi corretamente preenchido.\nMensagem de erro: " + e.getMessage() + "\n" + e.getCause(),
                    "Dados inconsistentes",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.updateTableProdutos(this.ctr.getProdutos());
            JOptionPane.showMessageDialog(this,
                "Produto cadastrado.",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void jButtonPesquisaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaProdutosActionPerformed
        List<Produto> searchResult = new ArrayList<>();
        String searchTerm = StringNormalizer.toNormalForm2(this.jTextFieldPesquisaProdutos.getText());
        for(int i = 0; i < this.jTableProdutos.getRowCount(); i++){
            Produto p = this.tmProduto.getObjectAt(i);
            String description = StringNormalizer.toNormalForm2(p.describe());

            System.out.println("PESQUISA: ["+ p.describe() +"] X ["+ searchTerm +"]");

            if (description.contains(searchTerm)) {
                System.out.println("CONTAINS!");
                searchResult.add(p);
            }
        }
        this.updateTableProdutos(searchResult);
    }//GEN-LAST:event_jButtonPesquisaProdutosActionPerformed

    private void jButtonShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllActionPerformed
        // TODO add your handling code here:
        this.updateTableProdutos(this.ctr.getProdutos());
    }//GEN-LAST:event_jButtonShowAllActionPerformed

    private void jButtonAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarProdutoActionPerformed
        // TODO add your handling code here:
        Produto p = this.getSelectedProduto();

        if(p == null){
            JOptionPane.showMessageDialog(this,
                "Nenhum produto foi selecionado",
                "Dados inconsistentes",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            this.ctr.updateProduto(p);
            JOptionPane.showMessageDialog(this,
                "Produto atualizado com sucesso",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Não foi possível atualizar este produto",
                "Erro ao atualizar.\nMensagem de erro: " + e.getMessage(),
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAtualizarProdutoActionPerformed

    private void jButtonRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverProdutoActionPerformed
        // TODO add your handling code here:

        Produto p = this.getSelectedProduto();

        if(p == null){
            JOptionPane.showMessageDialog(this,
                "Nenhum produto foi selecionado",
                "Dados inconsistentes",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            this.ctr.removeProduto(p);
            this.updateTableProdutos(this.ctr.getProdutos());
            JOptionPane.showMessageDialog(this,
                "Produto deletado com sucesso.",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Não foi possível remover o produto.\nMensagem de erro: " + e.getMessage() + "\n" + e.getCause(),
                "Erro ao deletar",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRemoverProdutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialog nwindow = new JDialog();
        nwindow.add(new JPanelSelectFornecedor(this.ctr));
        nwindow.pack();
        nwindow.setModal(true);
        nwindow.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonComprarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarProdutoActionPerformed
        Produto toBuy = this.getSelectedProduto();
        
        if(toBuy == null){
            JOptionPane.showMessageDialog(this,
                "Nenhum produto foi selecionado",
                "Dados inconsistentes",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            ProdutoLojaDao pjDao = new ProdutoLojaDao();
            System.err.println("ID PRODUTO A COMPRAR: " + toBuy.getId());
            List<ProdutoLoja> ljPrds = pjDao.executeQuery("FROM ProdutoLoja AS ProdutoLoja WHERE produto_id = '"+  toBuy.getId() +"'");
            ProdutoLoja ploja = ljPrds.size() >= 1 ? ljPrds.get(0) : null;
            
            if(ploja == null){
                this.ctr.addProdutoLoja(
                        toBuy, 
                        utils.parse.NumberParser.getIntegerFrom(this.jFormattedTextFieldQuantidade.getText()), 
                        utils.parse.NumberParser.getIntegerFrom(this.jFormattedTextFieldPrecoVenda.getText())
                );
            }else{
                ploja.setPrecoVenda(utils.parse.NumberParser.getIntegerFrom(this.jFormattedTextFieldPrecoVenda.getText()));
                ploja.setQuantidadeEstoque(ploja.getQuantidadeEstoque() + utils.parse.NumberParser.getIntegerFrom(this.jFormattedTextFieldQuantidade.getText()));
                this.ctr.updateProdutoLoja(ploja);
            }
            
            JOptionPane.showMessageDialog(this,
                "Produto comprado com sucesso.",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Não foi possível remover o produto.\nMensagem de erro: " + e.getMessage() + "\n" + e.getCause(),
                "Erro ao comprar",
                JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButtonComprarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descField;
    private javax.swing.JFormattedTextField fornecedorField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtualizarProduto;
    private javax.swing.JButton jButtonComprarProduto;
    private javax.swing.JButton jButtonPesquisaProdutos;
    private javax.swing.JButton jButtonRemoverProduto;
    private javax.swing.JButton jButtonShowAll;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecoVenda;
    private javax.swing.JFormattedTextField jFormattedTextFieldQuantidade;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListSelectedProduto;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelProdutos;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldPesquisaProdutos;
    private javax.swing.JTextField modeField;
    private javax.swing.JTextField nameField;
    private javax.swing.JFormattedTextField pDateField;
    private javax.swing.JRadioButton pRadioBtn;
    private javax.swing.JFormattedTextField priceField;
    private javax.swing.JButton registerBtn;
    private javax.swing.JFormattedTextField vDateField;
    // End of variables declaration//GEN-END:variables
}
