/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ProdutoLojaDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.fornecedores.Produto;
import model.loja.ItemCarrinho;
import model.loja.ProdutoLoja;
import model.loja.Venda;
import tabacariaControllers.Tabacaria;
import static view.comboboxModel.Descriptible.sep;
import view.comboboxModel.GeneralComboboxModel;

/**
 *
 * @author andre
 */
public class JPanelVenda extends javax.swing.JPanel {

    /**
     * Creates new form JPanelVenda
     */
    Venda vend;
    DefaultListModel l = new DefaultListModel();
    DefaultListModel m = new DefaultListModel();
    DefaultComboBoxModel dcModelProdLoja;
    GeneralComboboxModel<ProdutoLoja>  gcProdLoja = new GeneralComboboxModel<>();
    Venda v = new Venda();
   
    Tabacaria ctr;
    List<ItemCarrinho> cart = new ArrayList<>();
    
    public JPanelVenda(Tabacaria ctr) {
        this.ctr = ctr;
        vend = new Venda();
        initComponents();
        //updateList1();
        listAllProducts();
    }
    
    public void listAllProducts(){
         this.dcModelProdLoja = gcProdLoja.getComboBoxModelUsingDescription(this.ctr.getProdutosLoja());
         this.jListProducts.setModel(dcModelProdLoja);
    }
    
    void updateList1() {
        l.clear();
        List<ProdutoLoja> p = this.ctr.getProdutosLoja();
        for (ProdutoLoja el : p) {
            if (!m.contains(el)) {
                l.addElement(el);
            }
        }
        jListProducts.setModel(l);
    }

    void updateList2() {
        
    }
    
    public void listSelectedProducts(){
        
    }
    
    public void createCartProduct(){
        
    }
    
    public ProdutoLoja getSelectedProdutoLoja(){
        int selectedIndex = this.jListProducts.getSelectedIndex();
        if(selectedIndex < 0){
            return null;
        }
        ProdutoLoja p = null;
        String description = (String)this.dcModelProdLoja.getElementAt(selectedIndex);
        System.out.println(description);
        
        String arr[] = description.split(sep);
        Long parsedId = null;
        try{
            parsedId = Long.parseLong(arr[0]);
        }catch(Exception e){
            System.err.println("ERRO DE CONVERSÃO EM: Produto > id");
        }
        
        ProdutoLojaDao pjDao = new ProdutoLojaDao();
        List<ProdutoLoja> lst = pjDao.executeQuery("FROM ProdutoLoja AS ProdutoLoja WHERE id = " + parsedId);
        
        if(lst.size() >= 1){
            p = lst.get(0);
        }else{
            return null;
        }
        return p;
    }
    
    public void showSelected(){
        System.err.println("DEBUG: jTableProdutosPropertyChange");
        ProdutoLoja selected = this.getSelectedProdutoLoja();
        if(selected == null){
            System.err.println("PRODUTO SELECIONADO É NULL");
            return;
        }
        this.jListCart.removeAll();
        List<ProdutoLoja> lstSelected = new ArrayList<>();
        
        
        try{
            ItemCarrinho item = new ItemCarrinho(selected, utils.parse.NumberParser.getIntegerFrom(this.jFormattedTextFieldAmount.getText()));
            item.setID(0);
            this.cart.add(item);
            this.jListCart.setModel(new GeneralComboboxModel<ItemCarrinho>().getComboBoxModelUsingDescription(this.cart));
        }catch(Exception e){
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRealizVenda = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonStockToSell = new javax.swing.JButton();
        jButtonSellToStock = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCart = new javax.swing.JList<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaEndereco = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProducts = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jtNomeReceptor = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jFormattedTextFieldAmount = new javax.swing.JFormattedTextField();
        jLabelTotal = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Menu Vendas > Realizar vendas");

        jButtonStockToSell.setText(">");
        jButtonStockToSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStockToSellActionPerformed(evt);
            }
        });

        jButtonSellToStock.setText("<");
        jButtonSellToStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellToStockActionPerformed(evt);
            }
        });

        jListCart.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos no carrinho"));
        jListCart.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListCart.setToolTipText("");
        jScrollPane2.setViewportView(jListCart);

        jCheckBox1.setText("Entregar?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextAreaEndereco.setColumns(20);
        jTextAreaEndereco.setRows(5);
        jTextAreaEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço de entrega"));
        jTextAreaEndereco.setName(""); // NOI18N
        jScrollPane3.setViewportView(jTextAreaEndereco);

        jListProducts.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));
        jListProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProducts.setToolTipText("");
        jScrollPane1.setViewportView(jListProducts);

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Confirmar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jtNomeReceptor.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do receptor"));
        jtNomeReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeReceptorActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar todos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jFormattedTextFieldAmount.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));
        jFormattedTextFieldAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        jFormattedTextFieldAmount.setText("1");
        jFormattedTextFieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldAmountActionPerformed(evt);
            }
        });

        jLabelTotal.setText("Total a pagar: R$ 0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jButtonStockToSell))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jButtonSellToStock)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jtNomeReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotal))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButtonStockToSell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSellToStock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNomeReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)))
        );

        javax.swing.GroupLayout jPanelRealizVendaLayout = new javax.swing.GroupLayout(jPanelRealizVenda);
        jPanelRealizVenda.setLayout(jPanelRealizVendaLayout);
        jPanelRealizVendaLayout.setHorizontalGroup(
            jPanelRealizVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRealizVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelRealizVendaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanelRealizVendaLayout.setVerticalGroup(
            jPanelRealizVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRealizVendaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1102, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jPanelRealizVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(jPanelRealizVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStockToSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStockToSellActionPerformed
        showSelected();
        Venda v = new Venda(0, cart);
        this.jLabelTotal.setText("Total a pagar: R$" + v.getValorTotal());
    }//GEN-LAST:event_jButtonStockToSellActionPerformed

    private void jButtonSellToStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellToStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSellToStockActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        
        
        try{
            if(this.cart.size() == 0){
                throw new Exception("Nenhum produto foi selecionado");
            }
            if(!this.jCheckBox1.isSelected()){
                this.ctr.addVenda(0, this.cart);
            }else{
                if(!this.jtNomeReceptor.getText().isEmpty() || !this.jTextAreaEndereco.getText().isEmpty()){
                    this.ctr.addPedido(this.jtNomeReceptor.getText(), this.jTextAreaEndereco.getText(), 0, cart);
                }else{
                    JOptionPane.showMessageDialog(this,
                    "Campos incompletos",
                    "Dados inconsistentes",
                    JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            /*for(this.cart: ItemCarrinho item){
        
            }*/
            
            
            
            JOptionPane.showMessageDialog(this,
                "Venda realizada com sucesso.",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Não foi possível realizar a venda.\nMensagem de erro: " + e.getMessage() + "\n" + e.getCause(),
                "Erro ao vender",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jtNomeReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeReceptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeReceptorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jFormattedTextFieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldAmountActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonSellToStock;
    private javax.swing.JButton jButtonStockToSell;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFormattedTextFieldAmount;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JList<String> jListCart;
    private javax.swing.JList<String> jListProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRealizVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaEndereco;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtNomeReceptor;
    // End of variables declaration//GEN-END:variables
}
