/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.fornecedores.Fornecedor;
import model.fornecedores.Produto;
import tabacariaControllers.Tabacaria;
import utils.parse.StringNormalizer;
import view.comboboxModel.GeneralComboboxModel;
import view.tableModel.GeneralTableModel;

/**
 *
 * @author andre
 */
public class JPanelFornecedores extends javax.swing.JPanel {

    /**
     * Creates new form JPanelFornecedores
     */
    private Tabacaria ctrl;
    private GeneralTableModel<Fornecedor> tblModel;
    private Fornecedor selected;
    
    public JPanelFornecedores(Tabacaria ctrl) {
        this.ctrl = ctrl;
        initComponents();
        updateTable(ctrl.getFornecedores());
    }
    
    
    private void updateTable(List<Fornecedor> lst){
        String [] columns = new String[4];

        columns[0] = "id";
        columns[1] = "nome";
        columns[2] = "contato";
        columns[3] = "cnpj";

        this.tblModel = new GeneralTableModel<Fornecedor>(columns, lst);
        this.jTable.setModel(this.tblModel);
    }
    
    private void showSelected(){
        Fornecedor selected = this.getSelected();
        
        if(selected == null){
            System.err.println("SELECIONADO É NULL");
            return;
        }
        
        this.jListSelected.removeAll();
        
        List<Fornecedor> lstSelected = new ArrayList<>();
        lstSelected.add(selected);
        
        this.jListSelected.setModel(new GeneralComboboxModel<Fornecedor>().getComboBoxModelUsingDescription(lstSelected));
    }
    
    private Fornecedor getSelected(){
        int selectedIndex = this.jTable.getSelectedRow();
        if(selectedIndex < 0){
            return null;
        }
        return this.tblModel.getObjectAt(selectedIndex);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelForns = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jnameJtf = new javax.swing.JTextField();
        jcontatoJtf = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jcnpjJftf = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSelected = new javax.swing.JList<>();
        showAllBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jtfSearchTerm = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Menu Fornecedores");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTablePropertyChange(evt);
            }
        });
        jScrollPane13.setViewportView(jTable);

        deleteBtn.setText("Deletar");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Cadastrar Fornecedor");

        jnameJtf.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        jnameJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameJtfActionPerformed(evt);
            }
        });

        jcontatoJtf.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));
        jcontatoJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcontatoJtfActionPerformed(evt);
            }
        });

        jButtonRegister.setText("Cadastrar");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jcnpjJftf.setBorder(javax.swing.BorderFactory.createTitledBorder("CNPJ"));
        jcnpjJftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        jListSelected.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecionado"));
        jScrollPane1.setViewportView(jListSelected);

        showAllBtn.setText("Mostrar todos");
        showAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Pesquisar");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Atualizar");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFornsLayout = new javax.swing.GroupLayout(jPanelForns);
        jPanelForns.setLayout(jPanelFornsLayout);
        jPanelFornsLayout.setHorizontalGroup(
            jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornsLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelFornsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFornsLayout.createSequentialGroup()
                        .addComponent(jtfSearchTerm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFornsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jnameJtf, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jcontatoJtf)
                            .addComponent(jcnpjJftf)))
                    .addGroup(jPanelFornsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFornsLayout.createSequentialGroup()
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelFornsLayout.setVerticalGroup(
            jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornsLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnameJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllBtn)
                    .addComponent(searchBtn)
                    .addComponent(jtfSearchTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFornsLayout.createSequentialGroup()
                        .addComponent(jcontatoJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcnpjJftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonRegister)
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteBtn)
                            .addComponent(jButtonUpdate)))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelForns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelForns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        Fornecedor todelete = this.getSelected();

        if(todelete == null){
            JOptionPane.showMessageDialog(this,
                "Nenhum fornecedor foi selecionado",
                "Dados inconsistentes",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            this.ctrl.removeFornecedor(todelete);
            this.updateTable(this.ctrl.getFornecedores());
            JOptionPane.showMessageDialog(this,
                "Fornecedor deletado com sucesso.",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Não foi possível remover o fornecedor.\nMensagem de erro: " + e.getMessage() + "\n" + e.getCause(),
                "Erro ao deletar",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jnameJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameJtfActionPerformed

    private void jcontatoJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcontatoJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcontatoJtfActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        
        if(this.jcnpjJftf.getText().isEmpty() || this.jcontatoJtf.getText().isEmpty() || this.jnameJtf.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
        }else{
            try{
                this.ctrl.addFornecedor(0, jnameJtf.getText(), jcontatoJtf.getText(), jcnpjJftf.getText());
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Algum campo não foi corretamente preenchido.\nMensagem de erro: " + e.getMessage() + "\n" + e.getCause(),
                    "Dados inconsistentes",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.updateTable(this.ctrl.getFornecedores());
            JOptionPane.showMessageDialog(this,
                "Fornecedor cadastrado.",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
       this.showSelected();
    }//GEN-LAST:event_jTableMouseClicked

    private void jTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTablePropertyChange
        this.showSelected();
    }//GEN-LAST:event_jTablePropertyChange

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        List<Fornecedor> searchResult = new ArrayList<>();
        String searchTerm = StringNormalizer.toNormalForm2(this.jtfSearchTerm.getText());
        for(int i = 0; i < this.jTable.getRowCount(); i++){
            Fornecedor p = this.tblModel.getObjectAt(i);
            String description = StringNormalizer.toNormalForm2(p.describe());
            System.out.println("PESQUISA: ["+ p.describe() +"] X ["+ searchTerm +"]");
            if (description.contains(searchTerm)) {
                System.out.println("CONTAINS!");
                searchResult.add(p);
            }
        }
        this.updateTable(searchResult);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void showAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBtnActionPerformed
        this.updateTable(this.ctrl.getFornecedores());
    }//GEN-LAST:event_showAllBtnActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        Fornecedor updated = this.getSelected();

        if(updated == null){
            JOptionPane.showMessageDialog(this,
                "Nenhum fornecedor foi selecionado",
                "Dados inconsistentes",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            this.ctrl.updateFornecedor(updated);
            JOptionPane.showMessageDialog(this,
                "Fornecedor atualizado com sucesso",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Não foi possível atualizar este fornecedor",
                "Erro ao atualizar.\nMensagem de erro: " + e.getMessage(),
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JList<String> jListSelected;
    private javax.swing.JPanel jPanelForns;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JTable jTable;
    private javax.swing.JFormattedTextField jcnpjJftf;
    private javax.swing.JTextField jcontatoJtf;
    private javax.swing.JTextField jnameJtf;
    private javax.swing.JTextField jtfSearchTerm;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton showAllBtn;
    // End of variables declaration//GEN-END:variables
}
