/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author andre
 */
public class MainJFrame extends javax.swing.JFrame {

    public enum menuTabs {INICIO, VENDAS, REALIZAR_VENDA, LISTAR_VENDA, ENTREGAS, PRODUTOS, ESTOQUE, FUNCIONARIOS, 
        FORNECEDORES, RELATORIO, RELATORIO_VENDAS, RELATORIO_ENTREGAS, RELATORIO_ESTOQUE, RELATORIO_COMPRAS
    };

    public int menuTabToIndex(menuTabs tab){
        int i = 0;
        
        /*switch(tab){
            case INICIO:
                return 0;
            case VENDAS:
                return 1;
            case REALIZAR_VENDA:
                return 2;
            case LISTAR_VENDA:
                return 3;
            case ENTREGAS:
                return 4;
            case PRODUTOS:
                return 4;
            case ESTOQUE:
                return 5;
            case FUNCIONARIOS:
                return 6;
            case FORNECEDORES:
                return 7;
            case RELATORIO:
            case RELATORIO_VENDAS:
            case RELATORIO_COMPRAS:
            case RELATORIO_ENTREGAS:
            case RELATORIO_ESTOQUE:
                return 8;
                
            default:
                return 0;
        }*/
        
        if(tab == menuTabs.INICIO){
            return i;
        }
        i++;
        if(tab == menuTabs.VENDAS){
            return i;
        }
        i++;
        if(tab == menuTabs.REALIZAR_VENDA){
            return i;
        }
        i++;
        if(tab == menuTabs.LISTAR_VENDA){
            return i;
        }
        i++;
        if(tab == menuTabs.ENTREGAS){
            return i;
        }
        i++;
        if(tab == menuTabs.PRODUTOS){
            return i;
        }
        i++;
        if(tab == menuTabs.ESTOQUE){
            return i;
        }
        i++;
        if(tab == menuTabs.FUNCIONARIOS){
            return i;
        }
        i++;
        if(tab == menuTabs.FORNECEDORES){
            return i;
        }
        i++;
        if(tab == menuTabs.RELATORIO || tab == menuTabs.RELATORIO_COMPRAS || tab == menuTabs.RELATORIO_ENTREGAS || tab == menuTabs.RELATORIO_ESTOQUE || tab == menuTabs.RELATORIO_VENDAS){
            return i;
        }
        i++;

        return 0;
    }
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelVendas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelRealizVenda = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelListVendas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelEntregas = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelProdutos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelEstoque = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelFunc = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelForns = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelRelatorios = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVendasEntregas = new javax.swing.JMenu();
        jMenuItemIniciarVenda = new javax.swing.JMenuItem();
        jMenuItemInformarEntrega = new javax.swing.JMenuItem();
        jMenuProdutosEstoque = new javax.swing.JMenu();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuItemListarProdutos = new javax.swing.JMenuItem();
        jMenuItemVerifValidade = new javax.swing.JMenuItem();
        jMenuItemEstoque = new javax.swing.JMenuItem();
        jMenuFuncForn = new javax.swing.JMenu();
        jMenuFuncionarios = new javax.swing.JMenu();
        jMenuItemFuncCrud = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenu();
        jMenuItemFornCrud = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatVendas = new javax.swing.JMenuItem();
        jMenuItemRelatEntregas = new javax.swing.JMenuItem();
        jMenuItemRelatEstoque = new javax.swing.JMenuItem();
        jMenuItemCompras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TabacariaTrezeLogo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Developed by AHKKP");

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel3)
                .addContainerGap(461, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Início", jPanelInicio);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Menu Vendas");

        javax.swing.GroupLayout jPanelVendasLayout = new javax.swing.GroupLayout(jPanelVendas);
        jPanelVendas.setLayout(jPanelVendasLayout);
        jPanelVendasLayout.setHorizontalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 858, Short.MAX_VALUE))
        );
        jPanelVendasLayout.setVerticalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vendas", jPanelVendas);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Menu Vendas");

        javax.swing.GroupLayout jPanelRealizVendaLayout = new javax.swing.GroupLayout(jPanelRealizVenda);
        jPanelRealizVenda.setLayout(jPanelRealizVendaLayout);
        jPanelRealizVendaLayout.setHorizontalGroup(
            jPanelRealizVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRealizVendaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 858, Short.MAX_VALUE))
        );
        jPanelRealizVendaLayout.setVerticalGroup(
            jPanelRealizVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRealizVendaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Realizar venda", jPanelRealizVenda);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Menu Vendas");

        javax.swing.GroupLayout jPanelListVendasLayout = new javax.swing.GroupLayout(jPanelListVendas);
        jPanelListVendas.setLayout(jPanelListVendasLayout);
        jPanelListVendasLayout.setHorizontalGroup(
            jPanelListVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListVendasLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 858, Short.MAX_VALUE))
        );
        jPanelListVendasLayout.setVerticalGroup(
            jPanelListVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListVendasLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar vendas", jPanelListVendas);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Menu Entregas");

        javax.swing.GroupLayout jPanelEntregasLayout = new javax.swing.GroupLayout(jPanelEntregas);
        jPanelEntregas.setLayout(jPanelEntregasLayout);
        jPanelEntregasLayout.setHorizontalGroup(
            jPanelEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntregasLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 842, Short.MAX_VALUE))
        );
        jPanelEntregasLayout.setVerticalGroup(
            jPanelEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntregasLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entregas", jPanelEntregas);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Menu Produtos");

        javax.swing.GroupLayout jPanelProdutosLayout = new javax.swing.GroupLayout(jPanelProdutos);
        jPanelProdutos.setLayout(jPanelProdutosLayout);
        jPanelProdutosLayout.setHorizontalGroup(
            jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 842, Short.MAX_VALUE))
        );
        jPanelProdutosLayout.setVerticalGroup(
            jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos", jPanelProdutos);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Menu Estoque");

        javax.swing.GroupLayout jPanelEstoqueLayout = new javax.swing.GroupLayout(jPanelEstoque);
        jPanelEstoque.setLayout(jPanelEstoqueLayout);
        jPanelEstoqueLayout.setHorizontalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 851, Short.MAX_VALUE))
        );
        jPanelEstoqueLayout.setVerticalGroup(
            jPanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstoqueLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estoque", jPanelEstoque);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Menu Funcionários");

        javax.swing.GroupLayout jPanelFuncLayout = new javax.swing.GroupLayout(jPanelFunc);
        jPanelFunc.setLayout(jPanelFuncLayout);
        jPanelFuncLayout.setHorizontalGroup(
            jPanelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 803, Short.MAX_VALUE))
        );
        jPanelFuncLayout.setVerticalGroup(
            jPanelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Funcionários", jPanelFunc);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Menu Fornecedores");

        javax.swing.GroupLayout jPanelFornsLayout = new javax.swing.GroupLayout(jPanelForns);
        jPanelForns.setLayout(jPanelFornsLayout);
        jPanelFornsLayout.setHorizontalGroup(
            jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornsLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 791, Short.MAX_VALUE))
        );
        jPanelFornsLayout.setVerticalGroup(
            jPanelFornsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornsLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fornecedores", jPanelForns);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Menu Relatórios");

        javax.swing.GroupLayout jPanelRelatoriosLayout = new javax.swing.GroupLayout(jPanelRelatorios);
        jPanelRelatorios.setLayout(jPanelRelatoriosLayout);
        jPanelRelatoriosLayout.setHorizontalGroup(
            jPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatoriosLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 830, Short.MAX_VALUE))
        );
        jPanelRelatoriosLayout.setVerticalGroup(
            jPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatoriosLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatórios", jPanelRelatorios);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TabacariaTrezeLogoSmaller.png"))); // NOI18N
        jLabel2.setText("Tabacaria Treze System");

        jLabel12.setText("Developed by AHKKP");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)))
                        .addGap(21, 21, 21))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jMenuVendasEntregas.setText("Vendas e Entregas");

        jMenuItemIniciarVenda.setText("Iniciar venda");
        jMenuItemIniciarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIniciarVendaActionPerformed(evt);
            }
        });
        jMenuVendasEntregas.add(jMenuItemIniciarVenda);

        jMenuItemInformarEntrega.setText("Informar entrega");
        jMenuItemInformarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInformarEntregaActionPerformed(evt);
            }
        });
        jMenuVendasEntregas.add(jMenuItemInformarEntrega);

        jMenuBar1.add(jMenuVendasEntregas);

        jMenuProdutosEstoque.setText("Produtos e Estoque");

        jMenuProdutos.setText("Produtos");

        jMenuItemListarProdutos.setText("Listar Produtos");
        jMenuProdutos.add(jMenuItemListarProdutos);

        jMenuItemVerifValidade.setText("Verificar datas de validade");
        jMenuProdutos.add(jMenuItemVerifValidade);

        jMenuProdutosEstoque.add(jMenuProdutos);

        jMenuItemEstoque.setText("Estoque");
        jMenuProdutosEstoque.add(jMenuItemEstoque);

        jMenuBar1.add(jMenuProdutosEstoque);

        jMenuFuncForn.setText("Funcionários e Fornecedores");

        jMenuFuncionarios.setText("Funcionários");

        jMenuItemFuncCrud.setText("Cadastrar, Remover e Atualizar");
        jMenuFuncionarios.add(jMenuItemFuncCrud);

        jMenuFuncForn.add(jMenuFuncionarios);

        jMenuFornecedores.setText("Fornecedores");

        jMenuItemFornCrud.setText("Cadastrar, Remover e Atualizar");
        jMenuFornecedores.add(jMenuItemFornCrud);

        jMenuFuncForn.add(jMenuFornecedores);

        jMenuBar1.add(jMenuFuncForn);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelatVendas.setText("Vendas");
        jMenuRelatorios.add(jMenuItemRelatVendas);

        jMenuItemRelatEntregas.setText("Entregas");
        jMenuRelatorios.add(jMenuItemRelatEntregas);

        jMenuItemRelatEstoque.setText("Estoque");
        jMenuRelatorios.add(jMenuItemRelatEstoque);

        jMenuItemCompras.setText("Compras");
        jMenuRelatorios.add(jMenuItemCompras);

        jMenuBar1.add(jMenuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIniciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIniciarVendaActionPerformed
        this.jTabbedPane1.setSelectedIndex(this.menuTabToIndex(menuTabs.REALIZAR_VENDA));
    }//GEN-LAST:event_jMenuItemIniciarVendaActionPerformed

    private void jMenuItemInformarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInformarEntregaActionPerformed
        this.jTabbedPane1.setSelectedIndex(this.menuTabToIndex(menuTabs.ENTREGAS));
    }//GEN-LAST:event_jMenuItemInformarEntregaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFornecedores;
    private javax.swing.JMenu jMenuFuncForn;
    private javax.swing.JMenu jMenuFuncionarios;
    private javax.swing.JMenuItem jMenuItemCompras;
    private javax.swing.JMenuItem jMenuItemEstoque;
    private javax.swing.JMenuItem jMenuItemFornCrud;
    private javax.swing.JMenuItem jMenuItemFuncCrud;
    private javax.swing.JMenuItem jMenuItemInformarEntrega;
    private javax.swing.JMenuItem jMenuItemIniciarVenda;
    private javax.swing.JMenuItem jMenuItemListarProdutos;
    private javax.swing.JMenuItem jMenuItemRelatEntregas;
    private javax.swing.JMenuItem jMenuItemRelatEstoque;
    private javax.swing.JMenuItem jMenuItemRelatVendas;
    private javax.swing.JMenuItem jMenuItemVerifValidade;
    private javax.swing.JMenu jMenuProdutos;
    private javax.swing.JMenu jMenuProdutosEstoque;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuVendasEntregas;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanelEntregas;
    private javax.swing.JPanel jPanelEstoque;
    private javax.swing.JPanel jPanelForns;
    private javax.swing.JPanel jPanelFunc;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelListVendas;
    private javax.swing.JPanel jPanelProdutos;
    private javax.swing.JPanel jPanelRealizVenda;
    private javax.swing.JPanel jPanelRelatorios;
    private javax.swing.JPanel jPanelVendas;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
