/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.fornecedores.Produto;
import model.fornecedores.ProdutoPerecivel;
import tabacariaControllers.Tabacaria;
import utils.DateUtils;
import utils.parse.StringNormalizer;
import view.comboboxModel.GeneralComboboxModel;
import view.tableModel.GeneralTableModel;

/**
 *
 * @author andre
 */
public class MainJFrame extends javax.swing.JFrame {

    
    
    /**
     * Creates new form MainJFrame
     */
    private Tabacaria ctrl;
    public MainJFrame(Tabacaria ctrl) {
        this.ctrl = ctrl;
        initComponents();
    }
    
    

    
    /*****************************************************************************/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPaneLogo = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelBigLogo = new javax.swing.JLabel();
        jLabelDevelopedBy = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenuVendasEntregas = new javax.swing.JMenu();
        jMenuItemInformarEntrega = new javax.swing.JMenuItem();
        jMenuItemNovaVenda = new javax.swing.JMenuItem();
        jMenuProdutosEstoque = new javax.swing.JMenu();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuItemListarProdutos = new javax.swing.JMenuItem();
        jMenuItemVerifValidade = new javax.swing.JMenuItem();
        jMenuItemEstoque = new javax.swing.JMenuItem();
        jMenuFuncForn = new javax.swing.JMenu();
        jMenuFuncionarios = new javax.swing.JMenu();
        jMenuItemFuncCrud = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenu();
        jMenuItemFornCrud = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatVendas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TabacariaTrezeLogoSmaller.png"))); // NOI18N
        jLabelNome.setText("Tabacaria Treze System");

        jLabelBigLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBigLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/TabacariaTrezeLogo.png"))); // NOI18N
        jLabelBigLogo.setToolTipText("");
        jLabelBigLogo.setVerifyInputWhenFocusTarget(false);

        jLabelDevelopedBy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDevelopedBy.setText("Developed by AHKKP");

        javax.swing.GroupLayout jPaneLogoLayout = new javax.swing.GroupLayout(jPaneLogo);
        jPaneLogo.setLayout(jPaneLogoLayout);
        jPaneLogoLayout.setHorizontalGroup(
            jPaneLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneLogoLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabelDevelopedBy))
                    .addComponent(jLabelBigLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPaneLogoLayout.setVerticalGroup(
            jPaneLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addGap(123, 123, 123)
                .addComponent(jLabelBigLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabelDevelopedBy)
                .addGap(37, 37, 37))
        );

        jLabelNome.getAccessibleContext().setAccessibleDescription("");

        jMenuVendasEntregas.setText("Vendas e Entregas");

        jMenuItemInformarEntrega.setText("Informar entrega");
        jMenuItemInformarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInformarEntregaActionPerformed(evt);
            }
        });
        jMenuVendasEntregas.add(jMenuItemInformarEntrega);

        jMenuItemNovaVenda.setText("Nova venda");
        jMenuItemNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaVendaActionPerformed(evt);
            }
        });
        jMenuVendasEntregas.add(jMenuItemNovaVenda);

        menuBar.add(jMenuVendasEntregas);

        jMenuProdutosEstoque.setText("Produtos e Estoque");

        jMenuProdutos.setText("Produtos");

        jMenuItemListarProdutos.setText("Listar Produtos");
        jMenuItemListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarProdutosActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemListarProdutos);

        jMenuItemVerifValidade.setText("Verificar datas de validade");
        jMenuItemVerifValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerifValidadeActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemVerifValidade);

        jMenuProdutosEstoque.add(jMenuProdutos);

        jMenuItemEstoque.setText("Estoque");
        jMenuItemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoqueActionPerformed(evt);
            }
        });
        jMenuProdutosEstoque.add(jMenuItemEstoque);

        menuBar.add(jMenuProdutosEstoque);

        jMenuFuncForn.setText("Funcionários e Fornecedores");

        jMenuFuncionarios.setText("Funcionários");

        jMenuItemFuncCrud.setText("Cadastrar, Remover e Atualizar");
        jMenuItemFuncCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncCrudActionPerformed(evt);
            }
        });
        jMenuFuncionarios.add(jMenuItemFuncCrud);

        jMenuFuncForn.add(jMenuFuncionarios);

        jMenuFornecedores.setText("Fornecedores");

        jMenuItemFornCrud.setText("Cadastrar, Remover e Atualizar");
        jMenuItemFornCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornCrudActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuItemFornCrud);

        jMenuFuncForn.add(jMenuFornecedores);

        menuBar.add(jMenuFuncForn);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelatVendas.setText("Vendas");
        jMenuItemRelatVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatVendasActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatVendas);

        jMenuItem1.setText("Estoque");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem1);

        menuBar.add(jMenuRelatorios);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jPaneLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarProdutosActionPerformed
        // TODO add your handling code here:
        JDialog windowPPerson = new JDialog();
        windowPPerson.add(new JPanelProduto(this.ctrl));
        windowPPerson.pack();
        windowPPerson.setModal(true);
        windowPPerson.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarProdutosActionPerformed

    private void jMenuItemNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaVendaActionPerformed
        // TODO add your handling code here:
        JDialog windowPPerson = new JDialog();
        windowPPerson.add(new JPanelVenda(this.ctrl));
        windowPPerson.pack();
        windowPPerson.setModal(true);
        windowPPerson.setVisible(true);
    }//GEN-LAST:event_jMenuItemNovaVendaActionPerformed

    private void jMenuItemFornCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornCrudActionPerformed
        JDialog windowPPerson = new JDialog();
        windowPPerson.add(new JPanelFornecedores(this.ctrl));
        windowPPerson.pack();
        windowPPerson.setModal(true);
        windowPPerson.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornCrudActionPerformed

    private void jMenuItemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoqueActionPerformed
        JDialog windowPPerson = new JDialog();
        windowPPerson.add(new JPanelEstoque(this.ctrl));
        windowPPerson.pack();
        windowPPerson.setModal(true);
        windowPPerson.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstoqueActionPerformed

    private void jMenuItemInformarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInformarEntregaActionPerformed
        JDialog windowPPerson = new JDialog();
        windowPPerson.add(new JPanelEntregas(/*this.ctrl*/));
        windowPPerson.pack();
        windowPPerson.setModal(true);
        windowPPerson.setVisible(true);
    }//GEN-LAST:event_jMenuItemInformarEntregaActionPerformed

    private void jMenuItemVerifValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerifValidadeActionPerformed
        
    }//GEN-LAST:event_jMenuItemVerifValidadeActionPerformed

    private void jMenuItemFuncCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncCrudActionPerformed
        JDialog windowPPerson = new JDialog();
        windowPPerson.add(new JPanelFuncionarios(this.ctrl));
        windowPPerson.pack();
        windowPPerson.setModal(true);
        windowPPerson.setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncCrudActionPerformed

    private void jMenuItemRelatVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatVendasActionPerformed
        JDialog windowPPerson = new JDialog();
        windowPPerson.add(new JPanelRelatorios(this.ctrl));
        windowPPerson.pack();
        windowPPerson.setModal(true);
        windowPPerson.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatVendasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialog windowPPerson = new JDialog();
        windowPPerson.add(new JPanelEstoque(this.ctrl));
        windowPPerson.pack();
        windowPPerson.setModal(true);
        windowPPerson.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JLabel jLabelBigLogo;
    private javax.swing.JLabel jLabelDevelopedBy;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JMenu jMenuFornecedores;
    private javax.swing.JMenu jMenuFuncForn;
    private javax.swing.JMenu jMenuFuncionarios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemEstoque;
    private javax.swing.JMenuItem jMenuItemFornCrud;
    private javax.swing.JMenuItem jMenuItemFuncCrud;
    private javax.swing.JMenuItem jMenuItemInformarEntrega;
    private javax.swing.JMenuItem jMenuItemListarProdutos;
    private javax.swing.JMenuItem jMenuItemNovaVenda;
    private javax.swing.JMenuItem jMenuItemRelatVendas;
    private javax.swing.JMenuItem jMenuItemVerifValidade;
    private javax.swing.JMenu jMenuProdutos;
    private javax.swing.JMenu jMenuProdutosEstoque;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuVendasEntregas;
    private javax.swing.JPanel jPaneLogo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
